/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sdmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sdmessage.pb-c.h"
void   data__init
                     (Data         *message)
{
  static const Data init_value = DATA__INIT;
  *message = init_value;
}
size_t data__get_packed_size
                     (const Data *message)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data__pack
                     (const Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data__pack_to_buffer
                     (const Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Data *
       data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Data *)
     protobuf_c_message_unpack (&data__descriptor,
                                allocator, len, data);
}
void   data__free_unpacked
                     (Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   message_t__init
                     (MessageT         *message)
{
  static const MessageT init_value = MESSAGE_T__INIT;
  *message = init_value;
}
size_t message_t__get_packed_size
                     (const MessageT *message)
{
  assert(message->base.descriptor == &message_t__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_t__pack
                     (const MessageT *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_t__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_t__pack_to_buffer
                     (const MessageT *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_t__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageT *
       message_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageT *)
     protobuf_c_message_unpack (&message_t__descriptor,
                                allocator, len, data);
}
void   message_t__free_unpacked
                     (MessageT *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_t__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor data__field_descriptors[5] =
{
  {
    "ano",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Data, ano),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "preco",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Data, preco),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "marca",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Data, marca),
    &marca__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modelo",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Data, modelo),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "combustivel",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Data, combustivel),
    &combustivel__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data__field_indices_by_name[] = {
  0,   /* field[0] = ano */
  4,   /* field[4] = combustivel */
  2,   /* field[2] = marca */
  3,   /* field[3] = modelo */
  1,   /* field[1] = preco */
};
static const ProtobufCIntRange data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Data",
  "Data",
  "Data",
  "",
  sizeof(Data),
  5,
  data__field_descriptors,
  data__field_indices_by_name,
  1,  data__number_ranges,
  (ProtobufCMessageInit) data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_t__opcode__enum_values_by_number[11] =
{
  { "OP_BAD", "MESSAGE_T__OPCODE__OP_BAD", 0 },
  { "OP_ADD", "MESSAGE_T__OPCODE__OP_ADD", 10 },
  { "OP_GET", "MESSAGE_T__OPCODE__OP_GET", 20 },
  { "OP_DEL", "MESSAGE_T__OPCODE__OP_DEL", 30 },
  { "OP_SIZE", "MESSAGE_T__OPCODE__OP_SIZE", 40 },
  { "OP_GETMODELS", "MESSAGE_T__OPCODE__OP_GETMODELS", 50 },
  { "OP_GETLISTBYTEAR", "MESSAGE_T__OPCODE__OP_GETLISTBYTEAR", 60 },
  { "OP_ORDER", "MESSAGE_T__OPCODE__OP_ORDER", 70 },
  { "OP_ERROR", "MESSAGE_T__OPCODE__OP_ERROR", 99 },
  { "OP_BUSY", "MESSAGE_T__OPCODE__OP_BUSY", 100 },
  { "OP_READY", "MESSAGE_T__OPCODE__OP_READY", 101 },
};
static const ProtobufCIntRange message_t__opcode__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{30, 3},{40, 4},{50, 5},{60, 6},{70, 7},{99, 8},{0, 11}
};
static const ProtobufCEnumValueIndex message_t__opcode__enum_values_by_name[11] =
{
  { "OP_ADD", 1 },
  { "OP_BAD", 0 },
  { "OP_BUSY", 9 },
  { "OP_DEL", 3 },
  { "OP_ERROR", 8 },
  { "OP_GET", 2 },
  { "OP_GETLISTBYTEAR", 6 },
  { "OP_GETMODELS", 5 },
  { "OP_ORDER", 7 },
  { "OP_READY", 10 },
  { "OP_SIZE", 4 },
};
const ProtobufCEnumDescriptor message_t__opcode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "message_t.Opcode",
  "Opcode",
  "MessageT__Opcode",
  "",
  11,
  message_t__opcode__enum_values_by_number,
  11,
  message_t__opcode__enum_values_by_name,
  9,
  message_t__opcode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue message_t__c_type__enum_values_by_number[8] =
{
  { "CT_BAD", "MESSAGE_T__C_TYPE__CT_BAD", 0 },
  { "CT_DATA", "MESSAGE_T__C_TYPE__CT_DATA", 10 },
  { "CT_MARCA", "MESSAGE_T__C_TYPE__CT_MARCA", 20 },
  { "CT_YEAR", "MESSAGE_T__C_TYPE__CT_YEAR", 30 },
  { "CT_MODEL", "MESSAGE_T__C_TYPE__CT_MODEL", 40 },
  { "CT_RESULT", "MESSAGE_T__C_TYPE__CT_RESULT", 50 },
  { "CT_LIST", "MESSAGE_T__C_TYPE__CT_LIST", 60 },
  { "CT_NONE", "MESSAGE_T__C_TYPE__CT_NONE", 70 },
};
static const ProtobufCIntRange message_t__c_type__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{30, 3},{40, 4},{50, 5},{60, 6},{70, 7},{0, 8}
};
static const ProtobufCEnumValueIndex message_t__c_type__enum_values_by_name[8] =
{
  { "CT_BAD", 0 },
  { "CT_DATA", 1 },
  { "CT_LIST", 6 },
  { "CT_MARCA", 2 },
  { "CT_MODEL", 4 },
  { "CT_NONE", 7 },
  { "CT_RESULT", 5 },
  { "CT_YEAR", 3 },
};
const ProtobufCEnumDescriptor message_t__c_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "message_t.C_type",
  "C_type",
  "MessageT__CType",
  "",
  8,
  message_t__c_type__enum_values_by_number,
  8,
  message_t__c_type__enum_values_by_name,
  8,
  message_t__c_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor message_t__field_descriptors[6] =
{
  {
    "opcode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MessageT, opcode),
    &message_t__opcode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MessageT, c_type),
    &message_t__c_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MessageT, data),
    &data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "result",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(MessageT, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "models",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(MessageT, n_models),
    offsetof(MessageT, models),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cars",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MessageT, n_cars),
    offsetof(MessageT, cars),
    &data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_t__field_indices_by_name[] = {
  1,   /* field[1] = c_type */
  5,   /* field[5] = cars */
  2,   /* field[2] = data */
  4,   /* field[4] = models */
  0,   /* field[0] = opcode */
  3,   /* field[3] = result */
};
static const ProtobufCIntRange message_t__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 3 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor message_t__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "message_t",
  "MessageT",
  "MessageT",
  "",
  sizeof(MessageT),
  6,
  message_t__field_descriptors,
  message_t__field_indices_by_name,
  2,  message_t__number_ranges,
  (ProtobufCMessageInit) message_t__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue marca__enum_values_by_number[5] =
{
  { "MARCA_TOYOTA", "MARCA__MARCA_TOYOTA", 0 },
  { "MARCA_BMW", "MARCA__MARCA_BMW", 1 },
  { "MARCA_RENAULT", "MARCA__MARCA_RENAULT", 2 },
  { "MARCA_AUDI", "MARCA__MARCA_AUDI", 3 },
  { "MARCA_MERCEDES", "MARCA__MARCA_MERCEDES", 4 },
};
static const ProtobufCIntRange marca__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex marca__enum_values_by_name[5] =
{
  { "MARCA_AUDI", 3 },
  { "MARCA_BMW", 1 },
  { "MARCA_MERCEDES", 4 },
  { "MARCA_RENAULT", 2 },
  { "MARCA_TOYOTA", 0 },
};
const ProtobufCEnumDescriptor marca__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Marca",
  "Marca",
  "Marca",
  "",
  5,
  marca__enum_values_by_number,
  5,
  marca__enum_values_by_name,
  1,
  marca__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue combustivel__enum_values_by_number[4] =
{
  { "COMBUSTIVEL_GASOLINA", "COMBUSTIVEL__COMBUSTIVEL_GASOLINA", 0 },
  { "COMBUSTIVEL_GASOLEO", "COMBUSTIVEL__COMBUSTIVEL_GASOLEO", 1 },
  { "COMBUSTIVEL_ELETRICO", "COMBUSTIVEL__COMBUSTIVEL_ELETRICO", 2 },
  { "COMBUSTIVEL_HIBRIDO", "COMBUSTIVEL__COMBUSTIVEL_HIBRIDO", 3 },
};
static const ProtobufCIntRange combustivel__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex combustivel__enum_values_by_name[4] =
{
  { "COMBUSTIVEL_ELETRICO", 2 },
  { "COMBUSTIVEL_GASOLEO", 1 },
  { "COMBUSTIVEL_GASOLINA", 0 },
  { "COMBUSTIVEL_HIBRIDO", 3 },
};
const ProtobufCEnumDescriptor combustivel__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Combustivel",
  "Combustivel",
  "Combustivel",
  "",
  4,
  combustivel__enum_values_by_number,
  4,
  combustivel__enum_values_by_name,
  1,
  combustivel__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
